base_url = "https://csspacecoast.lumeh.org/"
title = "Christian Science on Florida's Space Coast"
default_language = "en"
compile_sass = true
output_dir = "docs"

[markdown]
smart_punctuation = true

[slugify]
anchors = "off"
